### ISSUE TITLE
License

### ISSUE THREAD

**Issue by saraedum** [flatsurf/e-antic#100]
What exactly is the license of this now? The antic headers say that their FLINT which is, according to that headers, GPL2+. The e-antic headers I looked at say LGPL3+.

It would seem to me that that means that e-antic cannot be released under the LGPL anymore. Then again, I don't really understand antic's license. A license file was just added that says LGPL2.1 but they already have another license file that says GPL2.

**Comment by videlec** [comment]
For the reference https://github.com/wbhart/antic/issues/43

**Comment by saraedum** [comment]
They clarified it's LGPL2.1. I still think it would be good to clarify in the README that this is LGPL3+.
