### ISSUE TITLE
Parent of result of binary operators depends on the order of arguments

### ISSUE THREAD

**Issue by saraedum** [flatsurf/e-antic#126]
When performing arithmetic of rational elements that live in different number fields, the parent of the result depends on the order of the elements:

Consider two number fields, `K` and `L`. Then the parent of `K(0) + L(0)` is `K` whereas the parent of `L(0) + K(0)` is `L`.

---

We change the current implementation and force elements to be in the same number field for arithmetic (unless one of the number fields is the trivial number field, i.e., the rationals.)

Since this is a breaking change, we print a deprecation warning and keep the old behavior for the time being.

To debug where exactly the deprecated behavior is used, one can set the environment variable `LIBEANTIC_STRICT_BINOP` to opt into the new behavior. Instead of a deprecation warning being printed, an exception is then throw. Such an exception can then be intercepted with a debugger to get a full stack trace.

**Comment by saraedum** [comment]
This is essentially a bug. The best thing here is for the result to live in the rational number field.

**Comment by saraedum** [comment]
@videlec it's a bit unclear to me what we want here.

Consider the rationals Q and two further number fields K, L.

Where should the results of arithmetic live when doing arithmetic with elements that are actually rationals but live in these fields? Say, I add a rational number in Q to a rational number in K. It seems natural that the result is in K again, i.e.,

Q + K = K

But then, what if I add two rationals in K and L? We cannot form the field that contains K and L (and we wouldn't want to I guess.) So should we have

K + L = Q?

Currently, we have

K + L = K
L + K = L

Which is also really strange.

If we change this to be

K + L = Q
L + K = Q

which at least makes + not depend on the order, then we would also have

K + K = Q
Q + K = Q

for consistency I guess?

**Comment by videlec** [comment]
I agree that it would be nice for commutative operations to actually be implemented commutative. What happens if we forbid `k + l` and `l + k`? To do such operation we can ask the user to do explicitely the conversion `Q(k) + Q(l)`.

**Comment by saraedum** [comment]
Sure, that's an option. It's a breaking change (like some of the other alternatives.) But I have no problem with calling the result e-antic 2.0.0 then.

**Comment by saraedum** [comment]
The current behavior could be deprecated and issue a warning first.

**Comment by videlec** [comment]
The deprecation makes sense. What is your preference for the future behavior?

**Comment by saraedum** [comment]
I like your proposal for this to be forbidden without explicit conversion. We are building a C/C++ library here so I don't think we need the convenience of an implicit coercion machinery.

**Comment by saraedum** [comment]
As discussed, we want to keep the current behavior if one of the operands' parents is our representation of the rationals, `Q[x]/(x)`.
