### ISSUE TITLE
Migrate integration checks from the master0 branch

### ISSUE THREAD

**Issue by saraedum** [flatsurf/e-antic#168]
The master0 branch has integration checks for SageMath. These can't work currently since e.g. antic is not in SageMath yet and SageMath has not been adapted for e-antic 1.0.0. Eventually, we'd like to have these tests on the master branch.

**Comment by mkoeppe** [comment]
I have created https://trac.sagemath.org/ticket/31588 for use as the target ticket on the Sage side.
