### ISSUE TITLE
Test failure on 32-bit arches

### ISSUE THREAD

**Issue by jamesjer** [flatsurf/e-antic#194]
I am attempting to build e-antic 1.0.1 for the Fedora Linux distribution.  The build succeeded on every 64-bit architecture, but tests failed on both 32-bit architectures (i686 and ARM).  In both cases, test-suite.log shows the following:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
t-cmp is a Catch v2.13.5 host application.
Run with -? for options

-------------------------------------------------------------------------------
Relational Operators with Integers - int
  Implications
-------------------------------------------------------------------------------
renfxx/t-cmp.cpp:48
...............................................................................

renfxx/t-cmp.cpp:76: FAILED:
  REQUIRE( not (a <= b) )
with expansion:
  false

-------------------------------------------------------------------------------
Relational Operators with Integers - long
  Implications
-------------------------------------------------------------------------------
renfxx/t-cmp.cpp:48
...............................................................................

renfxx/t-cmp.cpp:76: FAILED:
  REQUIRE( not (a <= b) )
with expansion:
  false

===============================================================================
test cases:     9 |     7 passed | 2 failed
assertions: 97081 | 97079 passed | 2 failed

FAIL renfxx/t-cmp (exit status: 2)
```

GDB shows that when this test fails, the value of b is -2147483648; i.e., the most negative integer, and the only integer besides zero that is the negation of itself.  Let me know if I can provide any other information.

**Comment by jamesjer** [comment]
I changed the test to not choose the most negative integer and got the same failure with -2147483647, so my guess that the most negative integer had something to do with it is wrong.

**Comment by saraedum** [comment]
@jamesjer I cannot reproduce this on an i386 running Debian.

What are the versions of the dependencies that you are using?

**Comment by jamesjer** [comment]
The dependencies have changed some since July 16, but I still see the issue.  Currently:

- antic 0.2.4
- arb 2.20
- binutils 2.37
- boost 1.76.0
- catch 2.13.5
- flint 2.8.0
- gcc 11.2.1
- glibc 2.34.9000
- mpfr 4.1.0 + post-release patches 1-13
- ntl 11.5.1

The build flags used by Fedora are as follows:
```
-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
```

Things I have tried, without success:

- Add -fwrapv to the build flags
- Fix this warning:
```
../e-antic/renf_elem_class.hpp:213:48: warning: 'renf_elem_t' violates the C++ One Definition Rule [-Wodr]
  213 |     std::add_lvalue_reference_t<::renf_elem_t> renf_elem_t() const;
      |                                                ^
renf_elem_class.cpp:661:17: note: return value type mismatch
  661 | ::renf_elem_t & renf_elem_class::renf_elem_t() const
      |                 ^
renf_elem_class.cpp:661:17: note: 'renf_elem_t' was previously declared here
```
I changed line 661 of libeantic/srcxx/renf_elem_class.cpp to this, to match the header:
```
std::add_lvalue_reference_t<::renf_elem_t> renf_elem_class::renf_elem_t() const
```
- Disable LTO

**Comment by saraedum** [comment]
@jamesjer any recommendations on how to reproduce this?

There does not seem to be a 32bit fedora image for docker and I am somewhat reluctant to create a VM from scratch here...

**Comment by jamesjer** [comment]
As mentioned in the linked pull request, `renf_elem_cmp_ui` can return values other than -1, 0, and 1 (namely 2, in this case).  If that shouldn't happen, we can dig deeper, but that commit does make all tests pass on i386 Fedora Rawhide.

You are right about there being no 32-bit Fedora image for docker.  I don't think Fedora distributes an i386 installer anymore.  That architecture is halfway to being dropped altogether.  If you have an x86_64 Fedora Rawhide machine, do this:

- sudo dnf install mock
- sudo usermod -a -G mock [your username here]
- Visit https://koji.fedoraproject.org/koji/ and type e-antic into the search bar
- Choose the topmost result that has an "fc36" in the name
- You should see a download link for a .src.rpm file.  Download it.
- mock -r fedora-rawhide-i386 --rebuild [name of the .src.rpm file]
- Once the test suite fails, add more tools to the mock chroot; e.g., mock -r fedora-rawhide-i386 --install gdb gcc-gdb-plugin less
- mock -r fedora-rawhide-i386 --shell
- su - mockbuild
- cd build/BUILD/e-antic-1.0.3

You are now sitting at a shell inside the directory where e-antic was built.
