### ISSUE TITLE
Distribute doc/ in tarball

### ISSUE THREAD

**Issue by saraedum** [flatsurf/e-antic#231]
Currently, doc/ is missing from the tarball because we are building the tarball --without-doc.

It should be included and maybe it should be in a shape that it could be installed locally. (Actually, building it is probably not very realistic since it requires an unreleased version of standardese.)

**Comment by jgmbenoit** [comment]
Is it a good idea to use not wide spread softwares to build package ?

**Comment by saraedum** [comment]
I am not sure what you are proposing exactly. Doxygen had a lot of limitations that we did not want to accept when writing the documentation here.

We intend for the documentation to be hosted on our website so using software that is not available in most distributions immediately was not much of a concern. In my experience, very few people use the installed documentation unless it's a man page but I might be mistaken. We aim to have very readable documentation in the header files which is somewhat hard to achieve with doxygen imho.

Anyway, the situation is of course not ideal. But maybe some projects have to begin to explore non-standard tools so these tools might become standard tools some day.

**Comment by jgmbenoit** [comment]
Can you at least put the output documents in the source tarball so that users without stable or permanent internet connection can have the manual on their box.

**Comment by saraedum** [comment]
We'll discuss whether we want to include this in the source tarball or distribute it separately. The (unversioned) built documentation can already be downloaded from https://github.com/flatsurf/e-antic/archive/refs/heads/gh-pages.zip at the moment.

**Comment by saraedum** [comment]
We'll make sure to distribute the built documentation as a separate tarball with every release.
