### ISSUE TITLE
release 1.0

### ISSUE THREAD

**Issue by videlec** [flatsurf/e-antic#26]
Prepare a new release 1.0

- [x] c++ interface #15 , #25, #28, #37
- [x] parallelization #38, #40, #41
- [x] 32 bits compatibility #61
- [ ] check normaliz compatibility
- [x] check flatsurf compatibility
- [x] eantic::pow needs to be implemented
- [x] drop inlined functions from headers that call into other libraries

**Comment by saraedum** [comment]
Should this be 1.0 since it's backwards incompatible?

**Comment by videlec** [comment]
thanks

**Comment by saraedum** [comment]
Can we bother normaliz to require C++17? That could simplify the operator implementation quite a bit I think.

**Comment by videlec** [comment]
I would be happier if we stick to C++11 (or if needed C++14).

**Comment by saraedum** [comment]
Ok, so let me write it with C++17 first and then backport to 11/14.

**Comment by saraedum** [comment]
So, should we start calling this one 1.0.0-rc.1?

**Comment by saraedum** [comment]
I think that we can actually release this once https://github.com/Normaliz/Normaliz/pull/373 has been merged.
