### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by saraedum** [flatsurf/e-antic#267]
We should produce a new release with FLINT 3 support.

The question is what should be the version number. The options are 2.0.0 or 1.4.0.

Now, in principle, there are no API changes here. There are of course ABI changes when building against FLINT 3 (and no changes when building against FLINT 2.) We bump the soname so for distributions such as debian there is no problem with 1.4.0.

However, distributions such as conda-forge ignore the soname but use the version number and expect that anything that was built against 1.3.0 can use any later 1.x release at runtime.

So, the easy solution is to call this 2.0.0.

Does that work for you @videlec?

**Comment by videlec** [comment]
2.0.0 works with me
